
import React from 'react';
import { motion } from 'framer-motion';

const VideoStory: React.FC = () => {
  const VIDEO_EMBED_URL = "https://www.youtube.com/embed/yglApEB7qlk";

  return (
    <div id="video-story" className="relative min-h-screen flex items-center justify-center section-padding bg-neutral-900/10 backdrop-blur-[2px]">
      <div className="section-container flex flex-col lg:flex-row items-center justify-center gap-16 lg:gap-24">
        
        {/* Text Content - Robust Hierarchy */}
        <div className="w-full lg:w-1/2 flex flex-col items-center lg:items-start text-center lg:text-left">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 1, ease: "easeOut" }}
            viewport={{ once: true }}
            className="max-w-xl w-full"
          >
            <h2 className="font-montserrat text-amber-500 text-[10px] md:text-xs tracking-[0.6em] font-black uppercase mb-8">
              CHAPTER III: THE ECHO
            </h2>
            
            <h3 className="font-playfair text-fluid-h2 italic leading-tight mb-10 text-white/95">
              My 3-Min AI <br className="hidden md:block"/> HireVue
            </h3>
            
            <p className="text-white/40 text-sm md:text-lg leading-relaxed font-normal font-montserrat tracking-wide">
              Here you can see my 3-MIN AI HireVue generated by ChatGPT+NotebookLM+Canva. It talks about my past work experience, a little about my current projects and most importantly what I plan to do next.
            </p>
          </motion.div>
        </div>

        {/* Video Player - Adaptive Aspect Container */}
        <motion.div 
          initial={{ opacity: 0, scale: 0.98 }}
          whileInView={{ opacity: 1, scale: 1 }}
          transition={{ duration: 1.2, delay: 0.2 }}
          viewport={{ once: true }}
          className="w-full lg:w-1/2 max-w-2xl xl:max-w-3xl"
        >
          <div className="relative aspect-video rounded-[2rem] overflow-hidden shadow-[0_30px_100px_rgba(0,0,0,0.6)] border border-white/5 group bg-black">
            <iframe 
              src={VIDEO_EMBED_URL}
              className="absolute inset-0 w-full h-full"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
              referrerPolicy="strict-origin-when-cross-origin"
              allowFullScreen
              title="Mridul Malani 3-Min AI HireVue"
            />
            {/* Cinematic Frame Detail */}
            <div className="absolute inset-0 pointer-events-none border border-white/10 rounded-[2rem] transition-all duration-1000 group-hover:border-amber-500/20" />
            <div className="absolute top-0 left-0 w-16 h-16 border-t border-l border-amber-500/30 rounded-tl-[2rem] pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity" />
          </div>
        </motion.div>
        
      </div>
    </div>
  );
};

export default VideoStory;
